In [1]:
import matplotlib.pyplot as plt
from Hubbard.plot import *
import numpy as np
from Hubbard.io import *

N = 20
L = 4
Ly = 1
d = 3
shape = 'square'
w = None
eqt = 'neq'
meth = 'trf'
R0 = np.array([3, 3, 7.2])
G = HubbardGraph(N,
                 R0=R0,
                 lattice=np.array([L, Ly], dtype=int),
                 trap=(52.26, 1000),
                 lc=(1550,),
                 ascatt=1770,
                 laser=780,
                 band=1,
                 dim=d,
                 avg=1,
                 sparse=True,
                 shape=shape,
                 waist=w,
                 equalize=False,
                 eqtarget=eqt,
                 eqmethod=meth,
                 lattice_symmetry=True,
                 symmetry=True,
                 verbosity=2)
G.equalize(target='vT')


DVR: dx=[0.15 0.15 0.36]w is set.
DVR: n=[20 20 20] is set.
DVR: R0=[3.  3.  7.2]w is set.
['x' 'y' 'z']-reflection symmetry is used.
param_set: trap parameter V0=52.26kHz w=1000nm
lattice: lattice shape is square; lattice constants set to: (1550, 1550)
lattice: lattice shape is square
lattice: Full lattice sizes: [4 1]
lattice: lattice constants: (1550, 1550)w
lattice: dx fixed to: [0.15 0.15 0.36]w
DVR: dx=[0.15 0.15 0.36]w is set.
DVR: n=[35 20 20] is set.
DVR: R0=[5.325 3.    7.2  ]w is set.
Equalize: scale_factor is not a number. Set to None.
Equalize: varying waist direction = None.
Equalize: method = trf
Equalize: quantities = vT

H_op: n=[35 20 20] dx=[0.15 0.15 0.36]w p=[1 1 1] Gaussian sparse diagonalization starts. Lowest 5 states are to be calculated.
H_solver: Gaussian Hamiltonian solved. Time spent: 0.47s.
H_solver: eigenstates memory usage:  0.61 MiB.
H_op: n=[35 20 20] dx=[0.15 0.15 0.36]w p=[-1  1  1] Gaussian sparse diagonalization starts. Lowest 5 states are to be ca

(array([1.02676629, 1.00480756, 1.00480756, 1.02676629]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[-2.34015874, -0.        ],
        [-0.77536134, -0.        ],
        [ 0.77536134, -0.        ],
        [ 2.34015874, -0.        ]]),
 {'Nfeval': 25,
  'cost': array([[0.00000000e+00, 1.23844663e-01, 2.10888018e+00],
         [0.00000000e+00, 1.23844643e-01, 2.10887874e+00],
         [0.00000000e+00, 1.23844661e-01, 2.10888164e+00],
         [0.00000000e+00, 1.23844427e-01, 2.10888025e+00],
         [0.00000000e+00, 1.23844782e-01, 2.10887980e+00],
         [0.00000000e+00, 3.73912263e-02, 1.17072119e-02],
         [0.00000000e+00, 3.73912130e-02, 1.17086945e-02],
         [0.00000000e+00, 3.73912173e-02, 1.17057464e-02],
         [0.00000000e+00, 3.73910194e-02, 1.17071624e-02],
         [0.00000000e+00, 3.73913066e-02, 1.17075880e-02],
         [0.00000000e+00, 2.60793771e-03, 5.15476839e-05],
         [0.00000000e+00, 2.60792547e-03, 5.30375