# Simultaneous diagonalization

In [2]:
import numpy as np
import numpy.linalg as la

R = [None, None]
V = [None, None]
R[0] = np.array([[0.,          0., - 0.68510884, 0.],
                 [0.,         0.,        0., - 0.68644896],
                 [-0.68510884, 0.,         0.,          0.],
                 [0., - 0.68644896, 0.,          0.]])
# [-0.68644896 -0.68510884  0.68510884  0.68644896]
V[0] = np.array([[0.,        0.70710678, - 0.70710678, 0.],
                 [0.70710678, 0.,  0., - 0.70710678],
                 [0.,      0.70710678, 0.70710678, 0.],
                 [0.70710678, 0.,    0.,     0.70710678]])
R[1] = np.array([[0., - 0.68510884, 0.,        0.],
                 [-0.68510884, 0.,         0.,         0.],
                 [0.,      0.,         0., - 0.68644896],
                 [0.,      0., - 0.68644896, 0.]])
# [-0.68644896 - 0.68510884  0.68510884  0.68644896]
V[1] = np.array([[0.,        0.70710678, - 0.70710678, 0.],
                 [0.,      0.70710678, 0.70710678, 0.],
                 [0.70710678, 0.,  0., - 0.70710678],
                 [0.70710678, 0.,    0.,       0.70710678]])
print(R[0] @ R[1] - R[1] @ R[0])

[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.00183805  0.        ]
 [ 0.         -0.00183805  0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [5]:
B = V[0].T @ R[1] @ V[0]
la.eigh(B)

(array([-0.68644896, -0.68510884,  0.68510884,  0.68644896]),
 array([[-0.5,  0.5, -0.5,  0.5],
        [-0.5,  0.5,  0.5, -0.5],
        [-0.5, -0.5, -0.5, -0.5],
        [-0.5, -0.5,  0.5,  0.5]]))

### New unitary 'optimization' method

In [1]:
from Hubbard.equalizer import *
import numpy as np
from scipy.optimize import minimize, shgo, dual_annealing

N = 20
R0 = np.array([3, 3, 7.2])

W = HubbardParamEqualizer(N,
                          R0=R0,
                          lattice=np.array([2, 2], dtype=int),
                          lc=(1500, 1500),
                          band=1,
                          dim=3,
                          avg=1 / 2,
                          sparse=True,
                          equalize=False,
                          symmetry=True)

eqV = True
fixed = False
W.eq_label = 'eq'

E, V, parity = eigen_basis(W)
R = locality_mat(W, V[0], parity[0])
np.set_printoptions(precision=4, suppress=True)
A1, U1 = singleband_optimize(W, E[0], V[0], parity[0])
# A2, U2 = singleband_diagonalize(W, E[0], V[0], parity[0])

DVR: dx=[0.15 0.15 0.36]w is set.
DVR: n=[20 20 20] is set.
DVR: R0=[3.  3.  7.2]w is set.
['x' 'y' 'z']-reflection symmetry is used.
param_set: trap parameter V0=104.52kHz w=1000nm
Triangular lattice size adjust to: [4 1]
lattice: dx is fixed at: [0.15 0.15 0.36]w
lattice: lattice shape is square
lattice: Full lattice sizes: [4]
lattice: lattice constants: [1.5 1.5 1.5]w
DVR: dx=[0.15 0.15 0.36]w is set.
DVR: n=[35 20 20] is set.
DVR: R0=[5.25 3.   7.2 ]w is set.
H_op: n=[35 20 20] dx=[0.15 0.15 0.36]w p=[1 1 1] Gaussian sparse diagonalization is enabled. Lowest 4 states are to be calculated.
H_op: n=[35 20 20] dx=[0.15 0.15 0.36]w p=[1 1 1] Gaussian operator constructed.
H_solver: diagonalize sparse hermitian matrix.
H_solver: Gaussian Hamiltonian solved. Time spent: 0.49s.
H_solver: eigenstates memory usage: 0.48 MiB.
H_op: n=[35 20 20] dx=[0.15 0.15 0.36]w p=[-1  1  1] Gaussian sparse diagonalization is enabled. Lowest 4 states are to be calculated.
H_op: n=[35 20 20] dx=[0.15 0.15

In [5]:
from tools.simdiag import simdiag

simdiag(R)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/Users/nottforestfc/mambaforge/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/jj/svh185nn5ks_1q784w4vd_600000gn/T/ipykernel_15421/4260071070.py", line 3, in <cell line: 3>
    simdiag(R)
  File "/Users/nottforestfc/Library/CloudStorage/OneDrive-RiceUniversity/Documents/Research/Optical tweezer on Fermi Hubbard/Computation/src/tools/simdiag.py", line 89, in simdiag
TypeError: Matricies must commute.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nottforestfc/mambaforge/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1993, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Users/nottforestfc/mambaforge/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.stru

In [3]:
print(np.real(A1))
print(np.real(U1))
print(A2)
print(U2)

[[-36.6954  -0.3805  -0.3276   0.0053   0.0233  -0.0008]
 [ -0.3805 -36.6954  -0.0053   0.3276   0.0008  -0.0233]
 [ -0.3276  -0.0053 -37.799    0.3749  -0.3276   0.0053]
 [  0.0053   0.3276   0.3749 -37.799    0.0053  -0.3276]
 [  0.0233   0.0008  -0.3276   0.0053 -36.6954   0.3805]
 [ -0.0008  -0.0233   0.0053  -0.3276   0.3805 -36.6954]]
[[-0.171  -0.171  -0.6645  0.6645 -0.171   0.171 ]
 [ 0.1663 -0.1663  0.6668  0.6668  0.1663  0.1663]
 [ 0.5     0.5    -0.     -0.     -0.5     0.5   ]
 [-0.4698 -0.4698  0.2418 -0.2418 -0.4698  0.4698]
 [-0.5     0.5     0.      0.      0.5     0.5   ]
 [ 0.4715 -0.4715 -0.2352 -0.2352  0.4715  0.4715]]
[[-37.0452   0.0548  -0.6128   0.1242  -0.0148   0.1242]
 [  0.0548 -37.0448   0.6109  -0.014    0.1242  -0.014 ]
 [ -0.6128   0.6109 -37.0998   0.1706  -0.1711   0.1706]
 [  0.1242  -0.014    0.1706 -37.0448   0.0548 -37.0448]
 [ -0.0148   0.1242  -0.1711   0.0548 -37.0452   0.0548]
 [  0.1242  -0.014    0.1706 -37.0448   0.0548 -37.0448]]
[[ 0.35