# Precision check

In [ ]:
import numpy.linalg as la
import numpy as np

a = np.array([[1, 2, 10], [4, 5, 6], [7, 8, 9]], dtype=np.float64)
a += a.T
a /= la.det(a)
eval, evec = la.eig(a)

np.set_printoptions(precision=16, suppress=False)
print(eval)
print(evec)


[-0.0520358699629884  0.012933664594878  -0.0029146013545786]
[[ 0.4463183511916375  0.7903009899569351  0.419790751044692 ]
 [ 0.4860241219848064  0.1798095894666008 -0.8552479549140999]
 [ 0.7513857080344796 -0.58574128829112    0.3038530252483643]]


In [ ]:
print(-0.0520359 + 0.0520358699629884)
print(-0.0029146 + 0.0029146013545786)
print(0.0129337 - 0.012933664594878)


-3.0037011600203556e-08
1.3545786003293925e-09
3.54051219991075e-08


It is possible to have 5 digits in single-to-double precision comparison.