# ```reportIO``` test

In [3]:
import reportIO as rep
import numpy as np

filename = 'haotian_example.ini'
report = rep.get_report(filename)

print(rep.s(report, "Parameters", "geometry"))
print(rep.f(report, "Parameters", "nx"))
print(rep.f(report, "Parameters", "nonExistItem"))
print(rep.f(report, "Parameters", "nonExistItem", 1))

square
2.0
nan
1


In [3]:
import reportIO as rep
import numpy as np

filename = 'haotian_example.ini'
report = rep.get_report(filename)

values2 = {
    "array_1d": np.linspace(0, 1, 10),
    "array_2d": np.eye(3, 3),
    "dict": {
        "A": 1,
        "B": 2
    },
}
rep.create_report(filename, "Output3", **values2)

print(rep.a(report, "Output3", "array_1d"))
print(rep.a(report, "Output3", "array_2d"))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
print(rep.a(report, "Output3", "dict"))

[]
