# ```reportIO``` test

In [10]:
import reportIO as rep
import numpy as np

filename = "rep_example.ini"
report = rep.get_report(filename)

print("grid =", rep.a(report, "Lattice_Parameters", "custom_potential_grid"))
print("value =", rep.a(report, "Lattice_Parameters", "custom_potential_value"))
print("t_ij =", rep.a(report, "Singleband_Parameters", "t_ij"))

grid = [array([-5.,  5.]), array([-5.,  5.]), array([0.])]
value = [[[1.]
  [2.]]

 [[3.]
  [4.]]]
t_ij = [[0.         0.50074887 0.50074857 0.29218494 0.02547812 0.00699203
  0.00699203 0.00701893]
 [0.50074887 0.         0.58428681 0.65195    0.01565009 0.05093612
  0.07753869 0.0075404 ]
 [0.50074857 0.58428681 0.         0.65195004 0.01564978 0.0775387
  0.05093616 0.00754039]
 [0.29218494 0.65195    0.65195004 0.         0.64911028 0.04293114
  0.04293108 0.04216438]
 [0.02547812 0.01565009 0.01564978 0.64911028 0.         0.60638569
  0.6063857  0.3387159 ]
 [0.00699203 0.05093612 0.0775387  0.04293114 0.60638569 0.
  0.5590528  0.68625086]
 [0.00699203 0.07753869 0.05093616 0.04293108 0.6063857  0.5590528
  0.         0.68625088]
 [0.00701893 0.0075404  0.00754039 0.04216438 0.3387159  0.68625086
  0.68625088 0.        ]]


In [1]:
import reportIO as rep
import numpy as np

filename = 'haotian_example.ini'
report = rep.get_report(filename)

print("geometry =", rep.s(report, "Parameters", "geometry"))
print("nx =", rep.f(report, "Parameters", "nx"))
print("none_var =", rep.f(report, "Parameters", "none_var"))
print("nonExistItem =", rep.f(report, "Parameters", "nonExistItem"))
print("nonExistItem =", rep.f(report, "Parameters", "nonExistItem", 1))


geometry = square
nx = 2.0
none_var = nan
nonExistItem = nan
nonExistItem = 1


In [2]:
import reportIO as rep
import numpy as np

filename = 'haotian_example.ini'
report = rep.get_report(filename)

print("boolean_var =", rep.b(report, "Parameters", "boolean_var"))
print("boolean_list =", rep.b(report, "Parameters", "boolean_list"))


boolean_var = False
boolean_list = [ True False False]


In [5]:
report["Output3"]

{'array_1d': '[0.0, 0.1111111111111111, 0.2222222222222222, 0.3333333333333333, 0.4444444444444444, 0.5555555555555556, 0.6666666666666666, 0.7777777777777777, 0.8888888888888888, 1.0]', 'array_2d': '[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]', 'dict': {'A': '1', 'B': '2'}}

In [1]:
import reportIO as rep
import numpy as np

filename = "haotian_example.ini"
report = rep.get_report(filename)

values2 = {
    "array_1d": np.linspace(0, 1, 10),
    "array_2d": np.eye(3, 3),
    "dict": {"A": 1, "B": 2},
}
rep.create_report(filename, "Output3", **values2)

print(rep.a(report, "Output3", "array_1d"))
print(rep.a(report, "Output3", "array_2d"))


Report loaded
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
print(rep.a(report, "Output3", "dict"))

[]
