# Test effect of pass initial vector to H_solver

In [2]:
# Directives on Jupyter
%reset
# Auto reload bootstrap.py
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import numpy as np

import sys
import os

module_path = os.path.abspath(os.path.join(".."))
if module_path not in sys.path:
    sys.path.append(module_path)


In [6]:
from HubbardTweezer.Hubbard.core import *
import numpy as np
from HubbardTweezer.Hubbard.io import *

N = 16
L = 3
Ly = 3
d = 3
shape = "square"
R0 = np.array([3, 3, 7.2])
G1 = MLWF(
    N,
    R0=R0,
    lattice=np.array([L, Ly], dtype=int),
    trap=(52.26, 1000),
    lc=(1550, 1600),
    ascatt=1770,
    laser=780,
    band=1,
    sparse=True,
    shape=shape,
    symmetry=True,
)


DVR: dx=[0.1875 0.1875 0.45  ]w is set.
DVR: n=[16 16 16] is set.
DVR: R0=[3.  3.  7.2]w is set.
['x' 'y' 'z']-reflection symmetry is used.
param_set: trap parameter V0=52.26kHz w=1000nm
Lattice: lattice shape is square; lattice constants set to: (1550, 1600)
lattice: lattice shape is square
lattice: Full lattice sizes: [3 3]
lattice: lattice constants: [1.55 1.6 ]w
lattice: dx fixed to: [0.1875 0.1875 0.45  ]w
DVR: dx=[0.1875 0.1875 0.45  ]w is set.
DVR: n=[24 24 16] is set.
DVR: R0=[4.55 4.6  7.2 ]w is set.


In [7]:
E, W = G1.H_solver(k=2)


H_op: n=[24 24 16] dx=[0.1875 0.1875 0.45  ]w p=[1 1 1] Gaussian sparse diagonalization starts. Lowest 2 states are to be calculated.
H_solver: Gaussian Hamiltonian solved. Time spent: 10.02s.
H_solver: eigenstates memory usage:  0.16 MiB.


10.7s

In [17]:
E

array([-0.71845736, -0.70207145])

In [18]:
W

array([[-1.44009320e-01,  4.86905856e-02],
       [-1.77815291e-01,  5.96569053e-02],
       [-1.19316855e-01,  3.90723092e-02],
       ...,
       [ 1.76603961e-17,  8.22895270e-18],
       [-2.01967374e-17, -4.69520864e-18],
       [-7.10878409e-18,  4.15909009e-18]])

In [14]:
G2 = MLWF(
    N,
    R0=R0,
    lattice=np.array([L, Ly], dtype=int),
    trap=(55, 1000),
    lc=(1550, 1600),
    ascatt=1770,
    laser=780,
    band=1,
    sparse=True,
    shape=shape,
    symmetry=True,
)


DVR: dx=[0.1875 0.1875 0.45  ]w is set.
DVR: n=[16 16 16] is set.
DVR: R0=[3.  3.  7.2]w is set.
['x' 'y' 'z']-reflection symmetry is used.
param_set: trap parameter V0=55kHz w=1000nm
Lattice: lattice shape is square; lattice constants set to: (1550, 1600)
lattice: lattice shape is square
lattice: Full lattice sizes: [3 3]
lattice: lattice constants: [1.55 1.6 ]w
lattice: dx fixed to: [0.1875 0.1875 0.45  ]w
DVR: dx=[0.1875 0.1875 0.45  ]w is set.
DVR: n=[24 24 16] is set.
DVR: R0=[4.55 4.6  7.2 ]w is set.


In [15]:
G2.H_solver(k=2)


H_op: n=[24 24 16] dx=[0.1875 0.1875 0.45  ]w p=[1 1 1] Gaussian sparse diagonalization starts. Lowest 2 states are to be calculated.
H_solver: Gaussian Hamiltonian solved. Time spent: 9.02s.
H_solver: eigenstates memory usage:  0.16 MiB.


(array([-0.724171  , -0.70869948]),
 array([[-1.50821789e-01, -4.58017487e-02],
        [-1.85254589e-01, -5.58257530e-02],
        [-1.22396006e-01, -3.60014622e-02],
        ...,
        [ 2.86650441e-18,  1.27573728e-18],
        [-4.06300407e-18, -5.72185549e-18],
        [ 6.23214677e-18,  1.54578118e-17]]))

9.7s

In [16]:
G2.H_solver(k=2, v0=W[:, 0])


H_op: n=[24 24 16] dx=[0.1875 0.1875 0.45  ]w p=[1 1 1] Gaussian sparse diagonalization starts. Lowest 2 states are to be calculated.
H_solver: Gaussian Hamiltonian solved. Time spent: 1.39s.
H_solver: eigenstates memory usage:  0.16 MiB.


(array([-0.724171  , -0.70869948]),
 array([[ 1.50821789e-01, -4.58017487e-02],
        [ 1.85254589e-01, -5.58257530e-02],
        [ 1.22396006e-01, -3.60014622e-02],
        ...,
        [ 1.11184407e-19,  3.96350739e-19],
        [ 4.10110057e-20,  3.86553644e-20],
        [-3.20486057e-21,  7.33071018e-20]]))

1.4s

Using previously solved eigenvector as initial for near parameter `eigsh` can save much time.