In [1]:
import numpy as np

a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
m = np.array([True, False, True])
a[m, :][:, m]


array([[0, 2],
       [6, 8]])

In [3]:
b = a.copy()
for i in range(2):
    b = b[m]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3